### ISSUE TITLE
CaseStatement factorisation

### ISSUE THREAD

**Issue by ElliotPozucek** [JustFallBack/Compilateur#6]
**In CaseStatement :**
CaseLabel := Factor { "," Factor }

**When INT..INT :** 
Create a new type **RANGE** in lexer. It is return by Number when the number is *INT..INT*.
Instead of handling loop in C++ **->** __cmp jae__ and __cmp jbe__.
Remove `jmp endCaseElement_X_Y` and replace it by `jmp endCaseElement_X+1_Y` and always write `endCaseElement_X+1_Y`tag at the end of *CaseStatement* **AND** don't remove `ENDCase_Y` tag (jmp to that tag when *Statement* is read).

**Comment by ColinLeDev** [comment]
Faire passer le type en argument pour comparaison de type 
CASE Exp OF {} END

Le type des {} = type de Exp

**Comment by ElliotPozucek** [comment]
Everything is done except **RANGE** when *INT..INT*.
